[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "egoavflow"
version = "0.1.0"
description = "EgoAVFlow: Robot Policy Learning with Active Vision from Human Egocentric Videos via 3D Flow"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["egoavflow*"]
